#!/bin/sh
#
# rplot: Rog-O-Matic XIV (CMU) Tue Feb  5 13:52:48 1985 - mlm
# Copyright (C) 1985 by A. Appel, G. Jacobson, L. Hamey, and M. Mauldin
#
./rogomatic -s | \
	colrm 48 | \
	./datesub | \
	sort -u -k 3n -k 1n -k 2n -k 5n -k 6 | \
	./rgmplot $*
