#!/bin/sh
#
# rplot: Rog-O-Matic XIV (CMU) Tue Feb  5 13:52:48 1985 - mlm
# Copyright (C) 1985 by A. Appel, G. Jacobson, L. Hamey, and M. Mauldin
#
colrm 48 | datesub | sort -u +2n +0n +1n +4n +5 | rgmplot $*
